id: P008191
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18637
  title: ཞེ་སའི་ཚིག་མཛོད་རབ་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    4c884814eb844f70900b02155f0ad074:
      image_group_id: I8LS18639
      title: ''
      volume_number: 1
      total_pages: 441
